// Generated by CoffeeScript 1.3.3
(function() {
  var EventEmitter, EventPlanner,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  EventEmitter = require('events').EventEmitter;

  EventPlanner = (function(_super) {

    __extends(EventPlanner, _super);

    function EventPlanner(namespace) {
      var _ref;
      this.namespace = namespace;
      if ((_ref = this.namespace) == null) {
        this.namespace = this.constructor.toString().match(/function\s*(\w+)/)[1];
      }
      EventPlanner.__super__.constructor.apply(this, arguments);
    }

    EventPlanner.prototype._addNamespace = function(name) {
      return [this.namespace, name].join('::');
    };

    EventPlanner.prototype.addListener = function(event, listener) {
      event = this._addNamespace(event);
      return EventPlanner.__super__.addListener.call(this, event, listener);
    };

    EventPlanner.prototype.on = function(event, listener) {
      event = this._addNamespace(event);
      return EventPlanner.__super__.on.call(this, event, listener);
    };

    EventPlanner.prototype.once = function(event, listener) {
      event = this._addNamespace(event);
      return EventPlanner.__super__.once.call(this, event, listener);
    };

    EventPlanner.prototype.removeListener = function(event, listener) {
      event = this._addNamespace(event);
      return EventPlanner.__super__.removeListener.call(this, event, listener);
    };

    EventPlanner.prototype.removeAllListeners = function(event) {
      var idx, name, _i, _len;
      if (typeof event === 'string') {
        event = [event];
      }
      for (name = _i = 0, _len = event.length; _i < _len; name = ++_i) {
        idx = event[name];
        event[idx] = this._addNamespace(name);
      }
      return EventPlanner.__super__.removeAllListeners.call(this, event);
    };

    EventPlanner.prototype.listeners = function(event) {
      event = this._addNamespace(event);
      return EventPlanner.__super__.listeners.call(this, event);
    };

    EventPlanner.prototype.emit = function() {
      arguments[0] = this._addNamespace(arguments[0]);
      return EventPlanner.__super__.emit.apply(this, arguments);
    };

    return EventPlanner;

  })(EventEmitter);

  module.exports = EventPlanner;

}).call(this);
